#!/bin/bash


# Author : YAHIA HOSNY 
# Date Created :27/12/2023 
#Last Modified : 08/01/2024

#Description
#'create a backup for all files in the home directory  ' 

#Usage
#'backup_script'

currentdir=$(pwd)


echo "Hello , ${USER,}"
echo "I will now back up your home directory,$HOME"
echo "You are running this script from ${currentdir} ."
echo "Therefore, I will save the backup in ${currentdir}"

tar -cf "$currentdir/my_backup_$(date +%d-%m-%Y_%H-%M-%S).tar" $HOME 2>/dev/null

echo "Backup Completed Successfully."

exit 0